/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteImport } from './routes/(auth)/_'
import { Route as appRouteImport } from './routes/(app)/_'
import { Route as ApiShapeIndexRouteImport } from './routes/api/shape/index'
import { Route as ApiInngestIndexRouteImport } from './routes/api/inngest/index'
import { Route as ApiChatIndexRouteImport } from './routes/api/chat/index'
import { Route as appIndexRouteImport } from './routes/(app)/_.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authSignupRouteImport } from './routes/(auth)/_.signup'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/_.reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/_.login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/_.forgot-password'
import { Route as appChatChatIdRouteImport } from './routes/(app)/_.chat/$chatId'

const authRoute = authRouteImport.update({
  id: '/(auth)/_',
  getParentRoute: () => rootRouteImport,
} as any)
const appRoute = appRouteImport.update({
  id: '/(app)/_',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapeIndexRoute = ApiShapeIndexRouteImport.update({
  id: '/api/shape/',
  path: '/api/shape/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestIndexRoute = ApiInngestIndexRouteImport.update({
  id: '/api/inngest/',
  path: '/api/inngest/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatIndexRoute = ApiChatIndexRouteImport.update({
  id: '/api/chat/',
  path: '/api/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRoute,
} as any)
const appChatChatIdRoute = appChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => appRoute,
} as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof appIndexRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/api/inngest/': typeof ApiInngestIndexRoute
  '/api/shape/': typeof ApiShapeIndexRoute
  '/chat/$chatId': typeof appChatChatIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof appIndexRoute
  '/api/chat': typeof ApiChatIndexRoute
  '/api/inngest': typeof ApiInngestIndexRoute
  '/api/shape': typeof ApiShapeIndexRoute
  '/chat/$chatId': typeof appChatChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_': typeof appRouteWithChildren
  '/(auth)/_': typeof authRouteWithChildren
  '/(auth)/_/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/_/login': typeof authLoginRoute
  '/(auth)/_/reset-password': typeof authResetPasswordRoute
  '/(auth)/_/signup': typeof authSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/_/': typeof appIndexRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/api/inngest/': typeof ApiInngestIndexRoute
  '/api/shape/': typeof ApiShapeIndexRoute
  '/(app)/_/chat/$chatId': typeof appChatChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/auth/$'
    | '/'
    | '/api/chat/'
    | '/api/inngest/'
    | '/api/shape/'
    | '/chat/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/auth/$'
    | '/'
    | '/api/chat'
    | '/api/inngest'
    | '/api/shape'
    | '/chat/$chatId'
  id:
    | '__root__'
    | '/(app)/_'
    | '/(auth)/_'
    | '/(auth)/_/forgot-password'
    | '/(auth)/_/login'
    | '/(auth)/_/reset-password'
    | '/(auth)/_/signup'
    | '/api/auth/$'
    | '/(app)/_/'
    | '/api/chat/'
    | '/api/inngest/'
    | '/api/shape/'
    | '/(app)/_/chat/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRoute: typeof appRouteWithChildren
  authRoute: typeof authRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatIndexRoute: typeof ApiChatIndexRoute
  ApiInngestIndexRoute: typeof ApiInngestIndexRoute
  ApiShapeIndexRoute: typeof ApiShapeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/_': {
      id: '/(auth)/_'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_': {
      id: '/(app)/_'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shape/': {
      id: '/api/shape/'
      path: '/api/shape'
      fullPath: '/api/shape/'
      preLoaderRoute: typeof ApiShapeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest/': {
      id: '/api/inngest/'
      path: '/api/inngest'
      fullPath: '/api/inngest/'
      preLoaderRoute: typeof ApiInngestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/': {
      id: '/api/chat/'
      path: '/api/chat'
      fullPath: '/api/chat/'
      preLoaderRoute: typeof ApiChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_/': {
      id: '/(app)/_/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_/signup': {
      id: '/(auth)/_/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRoute
    }
    '/(auth)/_/reset-password': {
      id: '/(auth)/_/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRoute
    }
    '/(auth)/_/login': {
      id: '/(auth)/_/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRoute
    }
    '/(auth)/_/forgot-password': {
      id: '/(auth)/_/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRoute
    }
    '/(app)/_/chat/$chatId': {
      id: '/(app)/_/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof appChatChatIdRouteImport
      parentRoute: typeof appRoute
    }
  }
}

interface appRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appChatChatIdRoute: typeof appChatChatIdRoute
}

const appRouteChildren: appRouteChildren = {
  appIndexRoute: appIndexRoute,
  appChatChatIdRoute: appChatChatIdRoute,
}

const appRouteWithChildren = appRoute._addFileChildren(appRouteChildren)

interface authRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteChildren: authRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  appRoute: appRouteWithChildren,
  authRoute: authRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatIndexRoute: ApiChatIndexRoute,
  ApiInngestIndexRoute: ApiInngestIndexRoute,
  ApiShapeIndexRoute: ApiShapeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
